import { UserProfile, Article, Message, Industry, UserEngagement } from '../types';

const CLAUDE_API_URL = "https://api.anthropic.com/v1/messages";

export async function callClaude(systemPrompt: string, messages: Message[]) {
  const apiKey = process.env.CLAUDE_API_KEY || "dummy-key"; 

  if (apiKey === "dummy-key") {
    await new Promise(resolve => setTimeout(resolve, 1500));
    return "This is a simulated AI response based on your profile and the latest news signals. In a production environment, this would be generated by Claude 3.5 Sonnet.";
  }

  try {
    const response = await fetch(CLAUDE_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: "claude-3-5-sonnet-20240620",
        max_tokens: 1024,
        system: systemPrompt,
        messages: messages.map(m => ({ role: m.role, content: m.content }))
      })
    });

    const data = await response.json();
    return data.content[0].text;
  } catch (error) {
    console.error("AI API Error:", error);
    throw error;
  }
}

/**
 * AGENTIC PIPELINE: Autonomous News Processing
 * Step 1: Entity & Sentiment Extraction (already mocked in data, but logic here)
 * Step 2: Personalized Ranking based on Profile + Engagement
 * Step 3: Synthesis & Delivery
 */

export function rankArticles(articles: Article[], user: UserProfile, engagement: UserEngagement): Article[] {
  return articles.map(article => {
    let score = 0;

    // 1. Sector Match (Base Score)
    if (user.industries.includes(article.sector)) score += 40;

    // 2. Portfolio Match (High Priority)
    const inPortfolio = user.portfolio.some(p => article.headline.includes(p.ticker) || article.summary.includes(p.ticker));
    if (inPortfolio) score += 50;

    // 3. Watchlist Match
    const inWatchlist = user.watchlistCompanies.some(c => article.headline.includes(c) || article.summary.includes(c));
    if (inWatchlist) score += 30;

    // 4. Engagement Retuning (Extra Credit)
    // If user frequently clicks/saves a sector, boost it
    const sectorEngagement = engagement.preferredSectors[article.sector] || 0;
    score += sectorEngagement * 5;

    // 5. Sentiment Alignment (Cognitive Preference)
    // (Simplified: Investors might prefer bullish news, Policy analysts neutral)
    if (user.role === 'Investor' && article.sentiment === 'Bullish') score += 10;
    if (user.role === 'Policy Analyst' && article.sentiment === 'Neutral') score += 10;

    return { ...article, relevanceScore: score };
  }).sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0));
}

export async function generateSynthesis(topArticles: Article[], user: UserProfile, format: string, language: string = 'English') {
  const context = topArticles.map(a => `[${a.sentiment}] ${a.headline}: ${a.summary}`).join('\n');
  const systemPrompt = getSystemPrompt(user, `Context: ${context}\nLanguage: ${language}`);
  
  const prompt = `Synthesize these ${topArticles.length} stories into a coherent ${format} briefing. 
  Focus on the cross-sector implications for a ${user.role}. 
  Output MUST be in ${language}. 
  If language is Hindi, use professional business Hindi (Hinglish is acceptable for technical terms).`;

  return await callClaude(systemPrompt, [{ role: 'user', content: prompt }]);
}

export function getSystemPrompt(user: UserProfile, context: string) {
  return `You are "My ET", an AI-native business newsroom. 
User Profile:
- Role: ${user.role}
- Industries: ${user.industries.join(', ')}
- Geography: ${user.geography}
- Reading Depth: ${user.depth}%
- Preferred Format: ${user.format}

${context}

Goal: Provide highly personalized, professional, and actionable business intelligence. 
Demonstrate deep synthesis—don't just list stories, explain WHY they matter together.`;
}
