import { Article, Company, MarketIndex } from './types';

export const MOCK_COMPANIES: Company[] = [
  { id: '1', name: 'Reliance Industries', ticker: 'RELIANCE', description: 'Energy to Telecom conglomerate', price: 3120.45, change: 1.2, sentiment: 75, logo: 'RI' },
  { id: '2', name: 'TCS', ticker: 'TCS', description: 'Global IT services leader', price: 4250.10, change: -0.5, sentiment: 60, logo: 'TCS' },
  { id: '3', name: 'HDFC Bank', ticker: 'HDFCBANK', description: 'India\'s largest private sector bank', price: 1780.30, change: 0.8, sentiment: 82, logo: 'HDFC' },
  { id: '4', name: 'Infosys', ticker: 'INFY', description: 'Next-gen digital services', price: 1640.20, change: -1.1, sentiment: 45, logo: 'INFY' },
  { id: '5', name: 'Zomato', ticker: 'ZOMATO', description: 'Food tech and quick commerce', price: 245.60, change: 4.5, sentiment: 90, logo: 'ZOM' },
  { id: '6', name: 'Adani Ports', ticker: 'ADANIPORTS', description: 'Largest commercial port operator', price: 1340.00, change: 2.1, sentiment: 68, logo: 'AP' },
  { id: '7', name: 'Bajaj Finance', ticker: 'BAJFINANCE', description: 'Diversified financial services', price: 7120.00, change: 0.3, sentiment: 72, logo: 'BF' },
  { id: '8', name: 'Paytm', ticker: 'PAYTM', description: 'Digital payments and financial services', price: 410.50, change: -2.4, sentiment: 30, logo: 'PAY' },
  { id: '9', name: 'ONGC', ticker: 'ONGC', description: 'Oil and natural gas explorer', price: 285.40, change: 1.5, sentiment: 55, logo: 'ONG' },
  { id: '10', name: 'Wipro', ticker: 'WIPRO', description: 'Information technology and consulting', price: 510.25, change: -0.2, sentiment: 50, logo: 'WIP' },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art1',
    category: 'Markets',
    headline: 'Nifty Hits Record High as FPI Inflows Surge in 2026',
    summary: 'Foreign portfolio investors pump $5B into Indian equities in Q1 2026, driven by stable macro indicators.',
    content: 'The Indian equity markets reached a historic milestone today as the Nifty 50 index crossed the 24,800 mark...',
    source: 'ET Markets',
    timeAgo: '2h ago',
    readTime: '4 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'Markets',
    entities: ['Nifty 50', 'FPI', 'Indian Economy']
  },
  {
    id: 'art2',
    category: 'AI & Tech',
    headline: 'Zomato\'s AI-Driven Logistics Cuts Delivery Times by 30%',
    summary: 'The food tech giant implements a new neural routing system across 50 cities, significantly boosting margins.',
    content: 'Zomato has announced a major breakthrough in its delivery operations...',
    source: 'ET Tech',
    timeAgo: '4h ago',
    readTime: '3 min',
    relevance: 'Portfolio Alert',
    sentiment: 'Bullish',
    sector: 'AI & Tech',
    entities: ['Zomato', 'AI', 'Logistics']
  },
  {
    id: 'art3',
    category: 'FinTech',
    headline: 'RBI Proposes New Framework for Digital Lending 2.0',
    summary: 'The central bank aims to tighten oversight on AI-based credit scoring models to prevent systemic risks.',
    content: 'The Reserve Bank of India has released a discussion paper on the next phase of digital lending...',
    source: 'ET Banking',
    timeAgo: '5h ago',
    readTime: '6 min',
    relevance: 'Watchlist',
    sentiment: 'Neutral',
    sector: 'FinTech',
    entities: ['RBI', 'Digital Lending', 'AI']
  },
  {
    id: 'art4',
    category: 'Energy',
    headline: 'Reliance Green Hydrogen Plant to Begin Operations in Gujarat',
    summary: 'The $10B facility marks a major step in India\'s transition to a net-zero economy by 2070.',
    content: 'Reliance Industries is set to commission its first green hydrogen giga-factory...',
    source: 'ET Energy',
    timeAgo: '6h ago',
    readTime: '5 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'Energy',
    entities: ['Reliance', 'Green Hydrogen', 'Net Zero']
  },
  {
    id: 'art5',
    category: 'Global Trade',
    headline: 'India-China Trade Deficit Narrows as Local Manufacturing Scales',
    summary: 'PLI schemes in electronics and chemicals show results as domestic production replaces imports.',
    content: 'Recent data from the Ministry of Commerce suggests a significant shift in trade dynamics...',
    source: 'ET Economy',
    timeAgo: '8h ago',
    readTime: '7 min',
    relevance: 'Watchlist',
    sentiment: 'Watch',
    sector: 'Global Trade',
    entities: ['Trade Deficit', 'PLI', 'Manufacturing']
  },
  {
    id: 'art6',
    category: 'Healthcare',
    headline: 'New AI-Powered Drug Discovery Hub Launched in Hyderabad',
    summary: 'A consortium of pharma majors and tech startups aim to reduce drug development time by 40%.',
    content: 'Hyderabad, the pharma capital of India, is embracing the AI revolution...',
    source: 'ET Health',
    timeAgo: '10h ago',
    readTime: '4 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'Healthcare',
    entities: ['Pharma', 'AI', 'Drug Discovery']
  },
  {
    id: 'art7',
    category: 'Markets',
    headline: 'HDFC Bank Q4 Results: Profit Jumps 18% on Strong Credit Growth',
    summary: 'The private lender beats analyst estimates despite rising cost of deposits in a high-interest environment.',
    content: 'HDFC Bank has reported its financial results for the quarter ended March 2026...',
    source: 'ET Markets',
    timeAgo: '12h ago',
    readTime: '5 min',
    relevance: 'Portfolio Alert',
    sentiment: 'Bullish',
    sector: 'Markets',
    entities: ['HDFC Bank', 'Banking', 'Q4 Results']
  },
  {
    id: 'art8',
    category: 'AI & Tech',
    headline: 'Infosys Signs $2B AI Transformation Deal with European Retailer',
    summary: 'The multi-year contract focuses on personalizing customer journeys using generative AI models.',
    content: 'Infosys has secured one of its largest deals in the current fiscal year...',
    source: 'ET Tech',
    timeAgo: '14h ago',
    readTime: '4 min',
    relevance: 'Watchlist',
    sentiment: 'Bullish',
    sector: 'AI & Tech',
    entities: ['Infosys', 'AI', 'Retail']
  },
  {
    id: 'art9',
    category: 'Real Estate',
    headline: 'Fractional Real Estate Investment Platforms See 200% Growth',
    summary: 'Retail investors flock to commercial property through SEBI-regulated SM REITs.',
    content: 'The landscape of real estate investment in India is undergoing a dramatic change...',
    source: 'ET Realty',
    timeAgo: '16h ago',
    readTime: '6 min',
    relevance: 'High Match',
    sentiment: 'Neutral',
    sector: 'Real Estate',
    entities: ['REITs', 'Real Estate', 'SEBI']
  },
  {
    id: 'art10',
    category: 'Manufacturing',
    headline: 'Tesla India Plant Rumors Resurface as Policy Incentives Align',
    summary: 'Government officials hint at a new EV manufacturing policy tailored for global premium brands.',
    content: 'Speculation about Tesla\'s entry into the Indian market has reached a fever pitch...',
    source: 'ET Auto',
    timeAgo: '18h ago',
    readTime: '5 min',
    relevance: 'Watchlist',
    sentiment: 'Watch',
    sector: 'Manufacturing',
    entities: ['Tesla', 'EV', 'Manufacturing']
  },
  {
    id: 'art11',
    category: 'FinTech',
    headline: 'UPI Internationalization: 5 More Countries Join the Network',
    summary: 'India\'s real-time payment system continues its global expansion, easing cross-border remittances.',
    content: 'The Unified Payments Interface (UPI) has reached a new milestone in its international journey...',
    source: 'ET Banking',
    timeAgo: '20h ago',
    readTime: '4 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'FinTech',
    entities: ['UPI', 'Payments', 'NPCI']
  },
  {
    id: 'art12',
    category: 'Markets',
    headline: 'SEBI Tightens Disclosure Norms for F&O Traders',
    summary: 'New regulations aim to increase transparency and protect retail investors in the derivatives segment.',
    content: 'The Securities and Exchange Board of India (SEBI) has introduced a series of new measures...',
    source: 'ET Markets',
    timeAgo: '22h ago',
    readTime: '6 min',
    relevance: 'Watchlist',
    sentiment: 'Neutral',
    sector: 'Markets',
    entities: ['SEBI', 'F&O', 'Trading']
  },
  {
    id: 'art13',
    category: 'AI & Tech',
    headline: 'India\'s First Indigenous Sovereign AI Model Unveiled',
    summary: 'Developed by a public-private partnership, the model is trained on 22 Indian languages.',
    content: 'In a significant boost to India\'s digital sovereignty, the first indigenous AI model...',
    source: 'ET Tech',
    timeAgo: '1d ago',
    readTime: '5 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'AI & Tech',
    entities: ['Sovereign AI', 'Digital India', 'LLM']
  },
  {
    id: 'art14',
    category: 'Energy',
    headline: 'Offshore Wind Policy Gets Cabinet Approval',
    summary: 'The government announces viability gap funding for the first 1GW of offshore wind projects.',
    content: 'The Union Cabinet has cleared a major policy hurdle for the offshore wind sector...',
    source: 'ET Energy',
    timeAgo: '1d ago',
    readTime: '7 min',
    relevance: 'Watchlist',
    sentiment: 'Bullish',
    sector: 'Energy',
    entities: ['Wind Energy', 'Renewables', 'Cabinet']
  },
  {
    id: 'art15',
    category: 'Real Estate',
    headline: 'Commercial Office Space Demand Hits 5-Year High',
    summary: 'Global Capability Centers (GCCs) drive absorption in Bengaluru, Hyderabad, and Pune.',
    content: 'The commercial real estate sector in India is witnessing a robust recovery...',
    source: 'ET Realty',
    timeAgo: '1d ago',
    readTime: '5 min',
    relevance: 'High Match',
    sentiment: 'Bullish',
    sector: 'Real Estate',
    entities: ['GCC', 'Office Space', 'Real Estate']
  }
];

export const MOCK_INDICES: MarketIndex[] = [
  { name: 'Sensex', value: 82145.60, change: 450.20, changePercent: 0.55, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 81000 + Math.random() * 2000 })) },
  { name: 'Nifty 50', value: 24812.30, change: 125.40, changePercent: 0.51, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 24000 + Math.random() * 1000 })) },
  { name: 'Nifty Bank', value: 52450.15, change: -120.30, changePercent: -0.23, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 51000 + Math.random() * 2000 })) },
  { name: 'S&P 500', value: 5420.10, change: 15.40, changePercent: 0.28, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 5300 + Math.random() * 200 })) },
  { name: 'Nasdaq', value: 18250.45, change: 85.20, changePercent: 0.47, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 17500 + Math.random() * 1000 })) },
  { name: 'USD/INR', value: 83.45, change: -0.12, changePercent: -0.14, sparkline: Array.from({ length: 10 }, (_, i) => ({ name: i.toString(), value: 83 + Math.random() * 0.5 })) },
];

export const TOPICS = ['Inflation', 'RBI Policy', 'SEBI', 'Fed', 'Oil', 'EVs', 'Semiconductors', 'IPOs', 'Startups', 'Geopolitics'];
export const PEOPLE = ['Uday Kotak', 'Radhika Gupta', 'Nithin Kamath', 'Piyush Goyal', 'Jerome Powell', 'Sam Altman'];
